### ISSUE TITLE
Have the function predictions run for all functions, rather than one selection

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#105]
Currently the function prediction is only done for whichever one is selected by the input argument. I'd like to change this so that all the functions are predicted and returned in one pass. This will eventually make it easier to use more expensive estimators and/or predict all the functions using one method (these are called multi-task methods).

Please do this on a new branch to keep is separate from other changes.

**Comment by scottdtaylor95** [comment]
So to clarify, you want the function to always return the prediction accuracy for "all", "Alter", and "notAlter"?

**Comment by aarmey** [comment]
No, return the results for every function—ADCC, ADCP, ADNP, etc., but do it for one of the options you list.

**Comment by scottdtaylor95** [comment]
Oh sorry I got confused by "function." Can do.

**Comment by aarmey** [comment]
Because of missing values this turned out to be much more complicated.
