### ISSUE TITLE
Performance vs. comp # plots

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#109]
I just merged some improvements to the factorization process, so it now should be quick enough to make a plot of prediction performance vs. component number. This will help us determine the right number of components.

**Comment by scottdtaylor95** [comment]
Which prediction metrics do you want to see?

**Comment by aarmey** [comment]
Hmm... let's say the correlation of cross-validated prediction for the Alter samples as plotted in Fig. 2A?

**Comment by scottdtaylor95** [comment]
Here's a plot of the first 10 decompositions, using the current setup we have now and passing the rank to perform_CMTF
![Screenshot (218)](https://user-images.githubusercontent.com/48601443/95286650-ca3a7c80-0818-11eb-83bc-30dd6187f2c4.png)

**Comment by aarmey** [comment]
This is helpful. I think it will still be useful to have a figure that plots this, since the result could be affected by other choices.
