### ISSUE TITLE
Is the pattern of missing data different for the genotype-specific measurements?

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#110]
It's been bothering me that the genotype-specific measurements are different from the general receptor:

<img width="208" alt="Screen Shot 2020-10-06 at 8 11 01 AM" src="https://user-images.githubusercontent.com/2065146/95220820-b573cf80-07ab-11eb-9ea5-8c4686092eec.png">

What I mean is, for example, IIA-H/R are more similar to each other than to IIA. I have a feeling this might be because the IIA measurements were done on more patients. If this is the case, I can add some regularization to "force" these receptors to behave the same in the factorization. If this is an artifact, this should improve the results.

We can start by someone checking if I'm right, and these were done on significantly different numbers of patients.

**Comment by scottdtaylor95** [comment]
Do you mean that there are more antigens tested with IIA vs IIA-H/R?

**Comment by scottdtaylor95** [comment]
I can say that IIA was tested with 24 antigens and H/R were tested with the same 35.

**Comment by aarmey** [comment]
Huh. Not the direction I was expecting but that's helpful to know.

**Comment by aarmey** [comment]
Ok, the next step here is to add the regularization for this. I'm going to wait for #114 to help with designing this.

**Comment by aarmey** [comment]
Just making note of what we discussed yesterday—you're looking in to how these are related to one another, because they indeed do vary in which measurements were performed.

**Comment by scottdtaylor95** [comment]
So I haven't managed to find a specific relationship between the data. However what I have noticed is that, typically, the nonspecific receptor (FcgRIIA, FcgRIIIA) is almost always the highest value by a good amount, the same allotype (H131 and F158) is usually in the middle, and the other allotype is the smallest, with few exceptions. don't know if that helps at all

**Comment by scottdtaylor95** [comment]
Is any sort of normalization done for these?

**Comment by aarmey** [comment]
Are you saying that, when the measurements are made in the same samples (same antigen and patient) they aren't correlated with one another?

We normalize all the data by z-scoring each chord (antigen-receptor pair) across patients.

**Comment by scottdtaylor95** [comment]
Looking at the pearson correlation, when looking at a particular antigen across patients, all three are somewhat correlated with each other. For FcgRIIa, R131 and H131 usually have a correlation coefficient of ~.9, H131 and the non-specific around .8 and R131 and non-specific around .76.

**Comment by aarmey** [comment]
Can you post the three A vs. B plots? I'm interested in how they co-vary and how they are scaled to one another...

**Comment by scottdtaylor95** [comment]
There are 3 A vs B plots per antigen, would you like to see a few of them? And would you just want them in scatterplot form?

**Comment by scottdtaylor95** [comment]
![Screenshot (202)](https://user-images.githubusercontent.com/48601443/96660071-7a21e680-12fd-11eb-9419-acde2b8b9037.png)

**Comment by scottdtaylor95** [comment]
Most of the plots for FcgRIIa look like this, with a few weird ones that are less correlated across the board

**Comment by aarmey** [comment]
Oh very interesting. It looks like the non-specific one is more sensitive—that would exactly explain this bowing effect.

Not sure what to do about this then... they're clearly measuring the same thing, but have a non-linear relationship with each other. The ADCC prediction seems to rely on this, too...

**Comment by scottdtaylor95** [comment]
Does it rely on all 3? Or could we remove the less sensitive one?

**Comment by aarmey** [comment]
Hmm... so, the Alter LASSO regression does rely on a mix of both measurements. **However**, LASSO is restricted to a linear relationship between inputs and outputs, and so one reason why it might rely on both is it's trying to capture a non-linear relationship between these and ADCC. I've had this in mind as a possibility, because these measurements are weighted both positively and negatively in their model, which doesn't make biological sense. (We know more R3 binding leads to more ADCC).

I think your suggestion is reasonable—we can certainly try removing the genotype-specific measurements, and see how it affects our results. It should just be a matter of slicing out those parts of the tensor.

**Comment by scottdtaylor95** [comment]
I did notice that the allotypes tend to have some negative values while the non-specific almost never does. Don't know if that affects weighting at all. At what step in the tensor building code should I try to slice? I'm not super familiar with it. Or would I just be able to test it by creating a separate data file missing those values?

**Comment by aarmey** [comment]
You could do it at the end of this function. This is what's always used to import the tensor:

https://github.com/meyer-lab/systemsSerology/blob/9c386c8e3e4444602607172253ae574ec53097bc/syserol/dataImport.py#L160

Each dimension is in the same order as Fig. 3 shows.

**Comment by aarmey** [comment]
Just not normalizing improves the predictions quite a bit! This skews the factors toward measurements that are larger (i.e. non-genotype), which further supports that removing the genotype-specific ones might help.

<img width="471" alt="Screen Shot 2020-10-20 at 9 57 26 PM" src="https://user-images.githubusercontent.com/2065146/96663794-6dae8580-131f-11eb-94e3-12fd332099e1.png">

**Comment by scottdtaylor95** [comment]
Removing all genotype specific detections didn't seem to improve ADCC prediction much, and also made some of the other functions slightly worse. I also tried running it for different component numbers. It seems to not have much effect on prediction, although oddly for 9 and 10 components it makes some of the function predictions have negative r2

**Comment by scottdtaylor95** [comment]
Having rerun it again using the build on master, it appears that while it slightly improves ADCC prediction, it also makes a few others worse. Also, I noticed that when I ran it the first time, some of the non-Alter predictions tended to have negative r2, but if I reran the figure in the notebook, they changed to be positive - is there some sort of warm start going on, or something like that?

**Comment by aarmey** [comment]
I'm not entirely sure where the randomness comes from, but I'd guess it's the cross-validation classes. Either way I think the conclusion is we should keep the genotype-specific measurements in. I have some adjustments that will help more forthcoming.

**Comment by aarmey** [comment]
@scottdtaylor95 can you put the non-genotype vs. genotype specific plots (like above) into a Fig. S2?

**Comment by scottdtaylor95** [comment]
Question - the three plots I showed above are for just one antigen. Would you like me to generate them for all shared antigens for all genotype/non-genotype groups? Or just pick a few at random? I think doing the former might be difficult, as there are a few groups and each has 20-25 antigens.

**Comment by aarmey** [comment]
Hmm... I'd try just throwing all the antigens in one plot first. If that doesn't work then yes, we can just pick a couple more or less at random.

**Comment by scottdtaylor95** [comment]
![Screenshot (209)](https://user-images.githubusercontent.com/48601443/97950402-92f1b980-1d4b-11eb-97d3-17a52fddc3b5.png)
![Screenshot (210)](https://user-images.githubusercontent.com/48601443/97950403-938a5000-1d4b-11eb-931f-469223dcf76d.png)
Here are the plots for the 2a and 3a receptors. A little messy, but seems to show the same trend. Is this okay? For reference, this is about 17 antigens (which is the entire overlapping set)

**Comment by aarmey** [comment]
Yep, this works. I'd just make the points smaller, and set the lower axis bounds at 0.
