### ISSUE TITLE
Figure 3 subjects plot

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#112]
It should be possible to see, from this plot, which rows are each class (EC, VC, etc). Additionally, the ordering of the rows is arbitrary, so it'd be an improvement to cluster patients based on similar factor values. Something like this might be useful to look at:

![jupyter_widget_nbviewer](https://user-images.githubusercontent.com/2065146/95257155-bff88e00-07d8-11eb-9df7-1966bfbe40bf.png)

See how category is shown by color, so you can see where it starts and ends.

**Comment by scottdtaylor95** [comment]
I've looked at this a bit - to get it to look like this (aka the easier method), each heatmap would need to be a separate figure due to how clustermap works. However I can play around with gridspec and make one figure, although without clustering, although it's a bit more work. Which would you prefer? If the latter is okay, would you prefer a colorbar legend for the different categories, or just labels on the axis, since all of our categories are grouped?

**Comment by aarmey** [comment]
I think just cleaning up the axis is fine, rather than using cluster map. It still could be useful to group similar items next to each other, so that it's easier to interpret the components. You can access the ordering of cluster map (even without plotting it) this way: https://github.com/mwaskom/seaborn/issues/1207

**Comment by scottdtaylor95** [comment]
What do you mean by cleaning up the axis? Trying to add the colored bars like the above figure?

**Comment by aarmey** [comment]
Yes, exactly.

**Comment by scottdtaylor95** [comment]
Okay, the only way I could find to do that without clustermap is to create a second heatmap plot for the colored bar and move it right next to the actual plot. It's a little weird but looks okay I think.

**Comment by aarmey** [comment]
The people working with the LINCS data figured out how to do this. Check with them first.

**Comment by scottdtaylor95** [comment]
I believe they switched the plot type to a clustermap, but I can double check.

**Comment by scottdtaylor95** [comment]
Yeah, it looks like the changed figure 2 from a heatmap to a clustermap to add the feature, unless I'm looking at the wrong thing. Unless you'd like me to swap to that, I can go ahead with the other strategy.

**Comment by aarmey** [comment]
Ok, sounds good.

**Comment by scottdtaylor95** [comment]
Which of the subplots would you like to have the added legend? Just the subject plot?

**Comment by aarmey** [comment]
What do you mean by legend?

**Comment by scottdtaylor95** [comment]
Sorry the category color bar, not sure what to call it.

**Comment by aarmey** [comment]
I think the other plots could be improved, but yes, lets just change the patient one for now.
