### ISSUE TITLE
Need a cartoon of the factorization process

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#115]
Because we're making a custom developed method, it'd be helpful to have a diagram explaining how this works.

**Comment by murphymadeleine21** [comment]
Do you have any softwares in mind for assembling this?

**Comment by aarmey** [comment]
I'd suggest Inkskape, or the lab can get you a copy of Affinity Designer after the free trial.

https://inkscape.org
https://affinity.serif.com/en-us/designer/
