### ISSUE TITLE
Figure 2 should include a plot of the weights for each prediction

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#126]
Right now we're printing these out in the console. They should be included visually as a bar plot for model interpretation.

**Comment by scottdtaylor95** [comment]
Do you want them plotted so that all component 1's are next to each other or each function is together? Also, for Alter and non-Alter or just the former?

**Comment by aarmey** [comment]
I’d group by function. Alter and non-Alter should have the same weights, so you can use either.

**Comment by murphymadeleine21** [comment]
Scott, are you going to work on this then? Or should I try to do this later today @scottdtaylor95

**Comment by scottdtaylor95** [comment]
You're welcome to if you want and have time, I have one or two other things I can do. Otherwise I can get to it soonish.
