### ISSUE TITLE
Use pseudo-inverse for glycan factors

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#127]
I think it's that patients with **any** glycan measurements have them **all**, but that some patients are simply missing all of the glycan measurements. Could you confirm? If so, this will greatly simplify factoring.

**Comment by scottdtaylor95** [comment]
Looking at the glycan csv, all patients there have some value for all glycans (including zero). The last patient has 0 for all values, but there are no NaNs.

**Comment by murphymadeleine21** [comment]
Yep, no NaNs for the patients included. However, there are only 98 patients, so technically it's missing data for 83 patients.

**Comment by aarmey** [comment]
Great, thanks.
