### ISSUE TITLE
Our replications of Alter paper predictions are worse than those in the paper

### ISSUE THREAD

**Issue by scottdtaylor95** [meyer-lab/systemsSerology#154]
With our current prediction methods, (ElasticNet for function and LogisticRegression for class) our replication of most of the Alter paper function and class predictions are worse than those in the paper. Some potential differences I can think of:

- There may be parameter and hyperparameter differences between our models and theirs
- The way we measure our accuracy is different
- The models themselves may differ in how they work due to different languages and functions

Some potential fixes:
- Allow parameters/Hyperparameters to vary to find more optimal solutions.
- Look through Alter code to understand how their model works and to find differences (Although this would probably require more knowledge of R)

**Comment by aarmey** [comment]
First step for this will be switching to glmnet and seeing how that affects performance.

**Comment by scottdtaylor95** [comment]
So I changed the settings of our current models to be more like those used in Alter and it appears that we are now predicting more similar values using the Alter data as in the paper. Specifically, turning off the normalization for the elasticnet, and using the recommended settings with the logistic regression gives values close to theirs, plus or minus a few percent. Unfortunately it didn't make our version predict much better.

**Comment by aarmey** [comment]
Alter pretty clearly indicates that they do normalize the data—we should still switch to glmnet to be comparable.

It's fine that we're not quite at the same performance, since we're still exploring model options.

**Comment by scottdtaylor95** [comment]
Alright, I'll try switching to glmnet. https://github.com/civisanalytics/python-glmnet/blob/master/glmnet/linear.py from what I see on this page, I'm going to run it with the Alter settings and then take the cv_mean_score_ as the accuracy?

**Comment by aarmey** [comment]
Yep

**Comment by scottdtaylor95** [comment]
Apparently if I do that it returns an array for cv_mean_score_, and I'm not sure how to interpret it, as there are many negative values.

**Comment by scottdtaylor95** [comment]
Alright, I think I have it set up, but I'm not getting the same values as in Alter still. I'm fairly close and as far as I can tell the parameters are the same, so I'm not sure where to go from here.

**Comment by aarmey** [comment]
In that make a PR and I'll review.

**Comment by aarmey** [comment]
I think this can potentially be entirely explained by Alter only looking at patients for which they have the full dataset. We should separate patients and calculate their accuracy separately based on whether they were included in Alter or not. This is the same as we do for the function predictions.
