### ISSUE TITLE
A consolidated list of the big figure additions

### ISSUE THREAD

**Issue by cyrillustan** [meyer-lab/systemsSerology#251]
Making a consolidated list of the big figure additions we should make:

- [ ] (S) Average prediction performance vs. # components and scaled variance between the antigen and glycan data.

- [ ] The variance explained by each component (antigen and glycan data, separately), for the 10 component factorization.

- [ ] (S) Bootstrapped weights of the "Alter" models.

- [ ] Imputation leaving individual measurements out, rather than tensor chords. This will then allow comparison to PCA, too.

- [ ] Variance estimates on the imputation by running it multiple times.

- [ ] Variance estimates on the prediction performance by running it multiple times with shuffled CV.

- [ ] Visualization of the classification decision boundaries.

- [ ] Possibly changing the variable importance measure to something more standard.

(S) indicates things to go in supplementary figures.

**Comment by Kimeiga** [comment]
I will try to do this one next!
 (S) Bootstrapped weights of the "Alter" models.

**Comment by Kimeiga** [comment]
Can also use Github Project (kanban board) to track progress in case any of these get blocked

**Comment by Kimeiga** [comment]
> I will try to do this one next!
> (S) Bootstrapped weights of the "Alter" models.

which reviewer comment was this in reference to?

**Comment by cyrillustan** [comment]
> > I will try to do this one next!
> > (S) Bootstrapped weights of the "Alter" models.
> 
> which reviewer comment was this in reference to?

I think this one comes from Dr Meyer's comment on the document. It is one piece of analysis we should include but didn't do in the first time.

**Comment by Kimeiga** [comment]
![image](https://user-images.githubusercontent.com/20587215/114462760-56e34000-9b98-11eb-85d6-6c630186e6c7.png)
Oh I see I'll try this one
https://aarmey.github.io/ml-for-bioe///outline/
