### ISSUE TITLE
Distinction between model.py and regression.py

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#61]
I'm not following the organization for what's in model.py vs. regression.py. Maybe we can put all of the classification in a classify.py, and then all the regression in a regression.py? This should make the imports in both files simpler, and the code easier to explore.

**Comment by murphymadeleine21** [comment]
Regression.py started off as the implementation of Alter's prediction methods. Model.py is our prediction methods.

**Comment by murphymadeleine21** [comment]
`patientComponents` is the only function in regression.py that I don't think is strictly Alter methods.. I believe you wrote this in the beginning but I don't think we're actually using it so we can perhaps get rid of it.

**Comment by aarmey** [comment]
Yep. Already removed it in my PR. :-)

**Comment by murphymadeleine21** [comment]
Okay, yes I see that now. I'm a bit confused about this different set up of organization though.. Some of the classification functions use regression methods? How will we distinguish?

**Comment by aarmey** [comment]
Anything that uses SVM would be in the classification file, and anything using Elastic net would be in the other.

**Comment by aarmey** [comment]
Another organization would be fine. Just should be some rule to it.
