### ISSUE TITLE
Separate R2X for the matrix and tensor

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#66]
Because of the changes we've made, it would be better to plot an individual R2X for the matrix and tensor in figure1.py. This should be just a matter of returning them individually rather than combined, then passing these numbers through the various functions.

**Comment by murphymadeleine21** [comment]
Okay. I'm trying to implement this and a bit confused because our R2XX function takes in the 4 different variables and returns 1 R2X, so I'm not sure how to get the individual matrix and tensor R2X

**Comment by murphymadeleine21** [comment]
something like `calcR2X(cube, None, tensorFac, None)`?

**Comment by aarmey** [comment]
Simplify the R2X function, then you can pass in either the matrix or tensor information:

```
def calcR2X(data, factor):
    """ Calculate R2X. """
    tensorErr = np.nanvar(tl.kruskal_to_tensor(factor) - data)
    return 1.0 - tensorErr / np.nanvar(data)
```
