### ISSUE TITLE
Re-explore the optimal number of components

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/systemsSerology#70]
Because we changed our model, 6 may no longer be optimal.

**Comment by murphymadeleine21** [comment]
Based on averages alone, it looks like Component 11 performs best, followed closely by 6. Might be worth it to look more closely at the specific accuracies though, not just the average.

functions = ["ADCD", "ADCC", "ADNP", "CD107a", "IFNy", "MIP1b"] (Ordering for accuracies below)
Component Number = 6. CP Accuracy: 0.6740331491712708, NV Accuracy: 0.6961325966850829, Function Accuracies: [0.66245615 0.46372677 0.53803872 0.39656835 0.46253852 0.55494691]

Component Number = 11. CP Accuracy: 0.6961325966850829, NV Accuracy: 0.7182320441988951, Function Accuracies: [0.67271301 0.48207145 0.53197589 0.42651276 0.35254335 0.61325689]
